"""v1.0.1 coverage: more task types per existing concept, plus a few new ones.

Each prompt is a distinct problem. Teaching-style items stay unverified unless
numeric/sympy is attached.
"""

from __future__ import annotations

COVERAGE_SPECS_V101: list[dict] = [
    {
        "concept_id": "python.variables",
        "domain": "programming",
        "education_level": "high_school",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "After `x = 3; y = x; x = 4`, what is y?",
        "answer": "3",
        "solution": "y still refers to the int 3. Rebinding x does not rebind y.",
        "numeric": {"got": 3, "expected": 3},
    },
    {
        "concept_id": "python.variables",
        "domain": "programming",
        "education_level": "high_school",
        "task_type": "applied_exercise",
        "language": "python",
        "prompt": "Why can `a, b = b, a` swap two names without a temporary in Python?",
        "answer": "The right-hand side is fully evaluated (as a tuple) before any assignment.",
        "solution": "Both b and a are read first. Then the names are rebound. A staggered a=b; b=a would lose a value.",
    },
    {
        "concept_id": "python.expressions",
        "domain": "programming",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "language": "python",
        "prompt": "A learner writes `avg = total / count` when both are ints and is surprised in Python 3 vs a C mental model of truncating. What does Python 3 `/` do, and which operator truncates toward zero for ints?",
        "answer": "`/` is true division (float). `//` is floor division for ints.",
        "solution": "7/2 is 3.5. 7//2 is 3. Mixing C's / with Python 3 is a common porting bug.",
    },
    {
        "concept_id": "python.expressions",
        "domain": "programming",
        "education_level": "high_school",
        "task_type": "applied_exercise",
        "language": "python",
        "prompt": "What is `True + True` in Python, and why is that legal?",
        "answer": "2; bool is a subclass of int, True==1.",
        "solution": "Boolean values participate in integer arithmetic. Prefer explicit int() if the intent is numeric.",
        "numeric": {"got": 2, "expected": 2},
    },
    {
        "concept_id": "python.conditionals",
        "domain": "programming",
        "education_level": "high_school",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "What does `elif` mean relative to a chain of `if`s, if the first `if` already matched?",
        "answer": "Later elif/else bodies are skipped; only one branch of the chain runs.",
        "solution": "elif is exclusive with prior matches. Separate ifs can all run.",
    },
    {
        "concept_id": "python.conditionals",
        "domain": "programming",
        "education_level": "high_school",
        "task_type": "applied_exercise",
        "language": "python",
        "prompt": "Why is `if xs:` preferred over `if len(xs) > 0:` for a possibly-None container you already know is a list?",
        "answer": "Empty lists are falsy; the length form is noisier and still wrong if xs could be None (TypeError).",
        "solution": "Truthiness of containers is the idiomatic emptiness test. Guard None separately if needed.",
    },
    {
        "concept_id": "python.loops",
        "domain": "programming",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "language": "python",
        "prompt": "A loop `for x in xs: xs.remove(x)` skips elements. Why?",
        "answer": "Mutating a list while iterating shifts later items into the current index, so they are never visited.",
        "solution": "Iterate a copy, or build a new list, or walk indices from the end.",
    },
    {
        "concept_id": "python.loops",
        "domain": "programming",
        "education_level": "high_school",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "How many times does `for i in range(2, 10, 3):` run, and what values of i?",
        "answer": "3 times: 2, 5, 8",
        "solution": "Start 2, step 3, stop before 10.",
        "numeric": {"got": 3, "expected": 3},
    },
    {
        "concept_id": "python.functions",
        "domain": "programming",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "language": "python",
        "prompt": "A function uses `print(total)` instead of `return total`. A caller `x = compute()` gets None. Why?",
        "answer": "print writes to stdout and the function still returns None by default.",
        "solution": "Return the value. Printing is a side effect, not a result.",
    },
    {
        "concept_id": "python.functions",
        "domain": "programming",
        "education_level": "high_school",
        "task_type": "applied_exercise",
        "language": "python",
        "prompt": "Why pass a large list into a function rather than copying it, if the function only reads?",
        "answer": "The parameter binds to the same object; a copy costs time and memory without changing read-only use.",
        "solution": "If the function might mutate, pass a copy or use a tuple.",
    },
    {
        "concept_id": "python.collections",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "debugging_exercise",
        "language": "python",
        "prompt": "`d = {}; d[ [1,2] ] = 3` raises. What exception class and why?",
        "answer": "TypeError; lists are unhashable so they cannot be dict keys.",
        "solution": "Use a tuple (1, 2) if the pair is the key.",
    },
    {
        "concept_id": "python.collections",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "What is `{1, 2, 2, 3}` after construction?",
        "answer": "{1, 2, 3}",
        "solution": "Sets drop duplicates. Display order is not a contract.",
    },
    {
        "concept_id": "python.classes",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "debugging_exercise",
        "language": "python",
        "prompt": "A class sets `id = []` in the class body. Instances append to `self.id`. Why do they share one list?",
        "answer": "id is a class attribute; self.id lookup finds the shared list unless rebound on the instance.",
        "solution": "Create a new list in __init__ as an instance attribute.",
    },
    {
        "concept_id": "python.exceptions",
        "domain": "programming",
        "education_level": "high_school",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "Does `finally` run if `except` re-raises? Yes or no.",
        "answer": "yes",
        "solution": "finally runs on the way out, including when an exception propagates.",
    },
    {
        "concept_id": "python.exceptions",
        "domain": "programming",
        "education_level": "high_school",
        "task_type": "applied_exercise",
        "language": "python",
        "prompt": "Why is catching Exception around a whole request handler often worse than catching a specific parse error?",
        "answer": "It hides unexpected bugs and can swallow programming errors you wanted to crash on.",
        "solution": "Catch the recoverable type near the source. Let unknown errors surface.",
    },
    {
        "concept_id": "python.modules",
        "domain": "programming",
        "education_level": "high_school",
        "task_type": "applied_exercise",
        "language": "python",
        "prompt": "Why can `from pkg import util` and `import pkg.util` bind different objects if util.py mutated after the first import?",
        "answer": "sys.modules caches the module; from-import binds names once. Reloading is not automatic.",
        "solution": "Treat imports as identity of the module object. Avoid mutable module-level state.",
    },
    {
        "concept_id": "python.iterators",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "What does `next(iter([]), 'missing')` return?",
        "answer": "missing",
        "solution": "The default is returned when the iterator is exhausted immediately.",
    },
    {
        "concept_id": "python.iterators",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "applied_exercise",
        "language": "python",
        "prompt": "Why is `zip(a, b)` not a list, and when does that matter?",
        "answer": "zip is lazy. A second iteration is empty unless you materialize or tee.",
        "solution": "Call list(zip(...)) if you need two passes.",
    },
    {
        "concept_id": "python.testing",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "debugging_exercise",
        "language": "python",
        "prompt": "A test asserts `self.assertTrue(xs)` on a list that should equal [1,2]. Why is that a weak test?",
        "answer": "Any nonempty list is truthy, including the wrong contents.",
        "solution": "Assert equality with the expected list.",
    },
    {
        "concept_id": "python.testing",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "unittest: should `setUp` run once per test method or once per class by default?",
        "answer": "once per test method",
        "solution": "setUpClass is the per-class hook. setUp isolates tests.",
    },
    {
        "concept_id": "cs.algorithms",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "debugging_exercise",
        "language": "python",
        "prompt": "A two-pointer scan assumes a sorted array but the caller passed insertion order. What class of bug is this?",
        "answer": "Broken precondition; the algorithm's invariant does not hold.",
        "solution": "Sort first if the API allows, or document and reject unsorted input.",
    },
    {
        "concept_id": "cs.algorithms",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "In a binary heap of n items, what is Theta of sift-down from the root in the worst case?",
        "answer": "Theta(log n)",
        "solution": "The height of a binary heap is Theta(log n).",
    },
    {
        "concept_id": "cs.data_structures",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "concept_explanation",
        "language": "python",
        "prompt": "When is a deque a better queue than a list using pop(0)?",
        "answer": "pop(0) is O(n); deque popleft is O(1).",
        "solution": "Lists are arrays. Deques are designed for ends.",
    },
    {
        "concept_id": "cs.data_structures",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "debugging_exercise",
        "language": "python",
        "prompt": "A hash table resizes at load 2/3 but the hash is `key % size` with size always even. Why can clustering get worse after resize if keys are even?",
        "answer": "If size is even, even keys all share one residue class modulo 2, and doubling can preserve a bad modulus.",
        "solution": "Use a prime table size or a mixing hash, not raw modulo of a structured key.",
    },
    {
        "concept_id": "cs.complexity",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "applied_exercise",
        "language": "python",
        "prompt": "You replace an O(n^2) loop with an O(n log n) sort-plus-scan. For n=10^6, which is expected to win, ignoring constants?",
        "answer": "O(n log n)",
        "solution": "n log n grows slower than n^2. Constants can still matter at small n.",
    },
    {
        "concept_id": "cs.complexity",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "debugging_exercise",
        "language": "python",
        "prompt": "A function is O(n) but repeatedly concatenates strings in a loop (`s += chunk`). Why can it still be quadratic in CPython?",
        "answer": "Each += may copy the growing string, totaling Theta(n^2) characters copied.",
        "solution": "Join a list of chunks, or use a buffer.",
    },
    {
        "concept_id": "cs.recursion",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "What is the maximum recursion depth roughly needed for a balanced binary tree of n nodes versus a linked-list-shaped tree, for a DFS?",
        "answer": "O(log n) vs O(n)",
        "solution": "Stack depth tracks tree height. Skewed trees are linear height.",
    },
    {
        "concept_id": "cs.recursion",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "applied_exercise",
        "language": "python",
        "prompt": "When is converting recursion to an explicit stack preferable to sys.setrecursionlimit?",
        "answer": "When input height can be thousands; raising the limit still risks crashing the process.",
        "solution": "An explicit stack uses heap memory and is bounded by your checks.",
    },
    {
        "concept_id": "cs.sql",
        "domain": "computer_science",
        "education_level": "introductory_college",
        "task_type": "debugging_exercise",
        "language": "sql",
        "prompt": "`SELECT COUNT(*)` vs `COUNT(col)` when col has NULLs. Which counts fewer rows, and why?",
        "answer": "COUNT(col) is fewer or equal; it skips NULLs. COUNT(*) counts rows.",
        "solution": "NULL is not a value of col. COUNT(*) is row cardinality.",
    },
    {
        "concept_id": "cs.sql",
        "domain": "computer_science",
        "education_level": "introductory_college",
        "task_type": "applied_exercise",
        "language": "sql",
        "prompt": "Why can `WHERE year = 2024` be sargable on an indexed year column while `WHERE YEAR(ts)=2024` often is not?",
        "answer": "Wrapping the column in a function hides the index; a range predicate on ts can use it.",
        "solution": "Write ts >= '2024-01-01' AND ts < '2025-01-01'.",
    },
    {
        "concept_id": "cs.http",
        "domain": "computer_science",
        "education_level": "introductory_college",
        "task_type": "debugging_exercise",
        "language": "python",
        "prompt": "A client treats HTTP 301 and 302 the same and changes POST to GET after redirect. Which status is specified to keep the method (in modern practice), and what goes wrong if you always GET?",
        "answer": "307/308 preserve method; converting POST to GET can drop the body and change a write into a read.",
        "solution": "Follow redirect rules per status. 301/302 historically mutated to GET in browsers.",
    },
    {
        "concept_id": "cs.http",
        "domain": "computer_science",
        "education_level": "introductory_college",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "Is HEAD supposed to have a response body? Yes or no.",
        "answer": "no",
        "solution": "HEAD returns the headers a GET would, without the body.",
    },
    {
        "concept_id": "cs.git",
        "domain": "computer_science",
        "education_level": "introductory_college",
        "task_type": "applied_exercise",
        "language": "python",
        "prompt": "Why is `git stash` a poor backup compared to a commit on a branch?",
        "answer": "Stashes are easy to drop, are not first-class history, and do not review well.",
        "solution": "WIP commits on a branch are fetchable, reflogged, and describable.",
    },
    {
        "concept_id": "cs.git",
        "domain": "computer_science",
        "education_level": "introductory_college",
        "task_type": "debugging_exercise",
        "language": "python",
        "prompt": "Detached HEAD after checkout of a tag: you commit, then checkout main. Where did the commit go if you did not create a branch?",
        "answer": "It is only in the reflog until garbage-collected; main does not include it.",
        "solution": "Create a branch at the commit before switching away.",
    },
    {
        "concept_id": "javascript.closures",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "applied_exercise",
        "language": "javascript",
        "prompt": "Why does wrapping a loop body in `{ let i = ... }` change what a later callback sees versus `var`?",
        "answer": "let is block-scoped per iteration when declared in the loop; var is function-scoped.",
        "solution": "for (let i=...) already creates a fresh binding. var does not.",
    },
    {
        "concept_id": "javascript.closures",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "simple_exercise",
        "language": "javascript",
        "prompt": "Does a closure copy primitive values from the outer scope at creation time, or keep a live binding?",
        "answer": "live binding",
        "solution": "It closes over the variable, not a snapshot, unless you copy explicitly.",
    },
    {
        "concept_id": "javascript.promises",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "debugging_exercise",
        "language": "javascript",
        "prompt": "`Promise.all` on [ok, reject, ok] — does it wait for the last success?",
        "answer": "No; it rejects when the first rejection happens (after that promise settles).",
        "solution": "Use allSettled if you need every outcome.",
    },
    {
        "concept_id": "javascript.promises",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "applied_exercise",
        "language": "javascript",
        "prompt": "Why is `await` in a loop sometimes required instead of `Promise.all`, even if it is slower?",
        "answer": "When each step depends on the previous result or must not run in parallel.",
        "solution": "Parallelism is incorrect for sequential side effects.",
    },
    {
        "concept_id": "rust.ownership",
        "domain": "programming",
        "education_level": "undergraduate",
        "task_type": "applied_exercise",
        "language": "rust",
        "prompt": "When is `Rc<T>` a reasonable escape from exclusive ownership, and when is it hiding a design problem?",
        "answer": "Reasonable for DAG-like shared ownership of immutable data. A smell if you need Rc<RefCell> everywhere to mutate.",
        "solution": "Prefer borrowing. Interior mutability plus shared ownership is easy to alias incorrectly.",
    },
    {
        "concept_id": "rust.ownership",
        "domain": "programming",
        "education_level": "undergraduate",
        "task_type": "simple_exercise",
        "language": "rust",
        "prompt": "Can you have two simultaneous `&mut` to the same local? Yes or no.",
        "answer": "no",
        "solution": "Aliasing XOR mutability: at most one exclusive borrow.",
    },
    {
        "concept_id": "go.concurrency",
        "domain": "programming",
        "education_level": "undergraduate",
        "task_type": "applied_exercise",
        "language": "go",
        "prompt": "Why is ranging over a channel a shutdown protocol, and who should close?",
        "answer": "Range stops after close and drain. Only the sender should close.",
        "solution": "Closing from the receiver races with sends (panic).",
    },
    {
        "concept_id": "go.concurrency",
        "domain": "programming",
        "education_level": "undergraduate",
        "task_type": "simple_exercise",
        "language": "go",
        "prompt": "Buffered channel of size 1: can a send proceed without a receiver waiting yet? Yes or no.",
        "answer": "yes",
        "solution": "The buffer holds one value. Unbuffered send always synchronizes.",
    },
    {
        "concept_id": "math.arithmetic",
        "domain": "mathematics",
        "education_level": "k5",
        "task_type": "applied_exercise",
        "prompt": "A recipe for 4 people uses 6 eggs. How many eggs for 6 people, scaling linearly?",
        "answer": "9",
        "solution": "6*(6/4)=9.",
        "numeric": {"got": 9, "expected": 9},
    },
    {
        "concept_id": "math.arithmetic",
        "domain": "mathematics",
        "education_level": "k5",
        "task_type": "debugging_exercise",
        "prompt": "A student computes 16-8-2 as 16-(8-2)=10. What went wrong?",
        "answer": "Subtraction is left-associative; 16-8-2 = (16-8)-2 = 6.",
        "solution": "Parentheses changed the meaning. Write (16-8)-2 or 16-8-2 consistently.",
        "numeric": {"got": 6, "expected": 6},
    },
    {
        "concept_id": "math.algebra",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "simple_exercise",
        "prompt": "Solve 2(x-3)=10. What is x?",
        "answer": "8",
        "solution": "x-3=5, x=8.",
        "numeric": {"got": 8, "expected": 8},
    },
    {
        "concept_id": "math.algebra",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "prompt": "Expanding (x-3)^2 a student writes x^2-9. What term was dropped?",
        "answer": "The middle term -6x; (x-3)^2 = x^2-6x+9.",
        "solution": "FOIL or (a-b)^2=a^2-2ab+b^2.",
    },
    {
        "concept_id": "math.functions",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "simple_exercise",
        "prompt": "If f(x)=2x+1 and g(x)=x^2, what is f(g(3))?",
        "answer": "19",
        "solution": "g(3)=9, f(9)=19.",
        "numeric": {"got": 19, "expected": 19},
    },
    {
        "concept_id": "math.functions",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "prompt": "A student computes (f ∘ g)(x) as f(x)*g(x). Name the error.",
        "answer": "Composition is not pointwise multiplication.",
        "solution": "(f ∘ g)(x)=f(g(x)). Product is a different operation.",
    },
    {
        "concept_id": "math.calculus",
        "domain": "mathematics",
        "education_level": "introductory_college",
        "task_type": "simple_exercise",
        "prompt": "d/dx of x^3 at x=2?",
        "answer": "12",
        "solution": "3x^2 at 2 is 12.",
        "numeric": {"got": 12, "expected": 12},
    },
    {
        "concept_id": "math.calculus",
        "domain": "mathematics",
        "education_level": "introductory_college",
        "task_type": "debugging_exercise",
        "prompt": "A student says the derivative of a constant 7 is 7. Correction?",
        "answer": "The derivative of a constant is 0.",
        "solution": "Slope of a horizontal line is zero. 7 is the function value, not the slope.",
        "numeric": {"got": 0, "expected": 0},
    },
    {
        "concept_id": "math.geometry",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "prompt": "Someone uses area=2πr for a circle of radius 4. What quantity did they compute instead, and what is the area in terms of pi?",
        "answer": "They computed circumference; area is 16*pi.",
        "solution": "C=2πr, A=πr^2=16π.",
        "sympy": {"got": "16*pi", "expected": "16*pi"},
    },
    {
        "concept_id": "math.geometry",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "concept_explanation",
        "prompt": "Why does SSS congruence not need a separate 'SSA' twin in Euclidean geometry?",
        "answer": "SSA is not a congruence theorem; two triangles can share SSA data and not be congruent (ambiguous case).",
        "solution": "SSS uniquely determines a triangle up to congruence. SSA does not.",
    },
    {
        "concept_id": "math.trigonometry",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "prompt": "sin(30°) is computed as 0.5 but the calculator was in radians. What goes wrong conceptually?",
        "answer": "The student mixed degree measure with a radian-mode evaluation.",
        "solution": "sin(30 rad) is not 1/2. Convert or switch mode.",
    },
    {
        "concept_id": "math.trigonometry",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "applied_exercise",
        "prompt": "A right triangle has opposite 5 and hypotenuse 13. What is sin of that angle as a reduced fraction?",
        "answer": "5/13",
        "solution": "sin=opp/hyp=5/13.",
        "numeric": {"got": 0.3846153846, "expected": 0.3846153846},
    },
    {
        "concept_id": "math.discrete",
        "domain": "mathematics",
        "education_level": "undergraduate",
        "task_type": "debugging_exercise",
        "prompt": "Counting passwords of length 2 from 10 symbols with repetition, a student uses C(10,2). What should they use?",
        "answer": "10^2 = 100; order matters and repetition is allowed.",
        "solution": "C(10,2) is unordered distinct pairs.",
        "numeric": {"got": 100, "expected": 100},
    },
    {
        "concept_id": "math.discrete",
        "domain": "mathematics",
        "education_level": "undergraduate",
        "task_type": "applied_exercise",
        "prompt": "How many edges in K_5, the complete graph on 5 vertices?",
        "answer": "10",
        "solution": "C(5,2)=10.",
        "numeric": {"got": 10, "expected": 10},
    },
    {
        "concept_id": "math.probability",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "prompt": "Two fair coins. A student says P(two heads)=1/3 because HH,HT,TH 'wait they listed TT too' — they listed HH, HT, TT and dropped TH. What is the real probability?",
        "answer": "1/4",
        "solution": "Four equally likely outcomes; only HH.",
        "numeric": {"got": 0.25, "expected": 0.25},
    },
    {
        "concept_id": "math.probability",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "applied_exercise",
        "prompt": "P(A)=0.3, P(B)=0.5, disjoint. What is P(A or B)?",
        "answer": "0.8",
        "solution": "Add when disjoint: 0.3+0.5.",
        "numeric": {"got": 0.8, "expected": 0.8},
    },
    {
        "concept_id": "math.linear_algebra",
        "domain": "mathematics",
        "education_level": "undergraduate",
        "task_type": "debugging_exercise",
        "prompt": "A student multiplies 2x2 matrices by multiplying matching entries (Hadamard). When is that not matrix multiplication?",
        "answer": "Always, unless they meant the Schur product; standard AB uses row-column dots.",
        "solution": "(AB)_{ij}=row i of A dot column j of B.",
    },
    {
        "concept_id": "math.linear_algebra",
        "domain": "mathematics",
        "education_level": "undergraduate",
        "task_type": "applied_exercise",
        "prompt": "What is the identity matrix I_2 times [[1,2],[3,4]]?",
        "answer": "[[1, 2], [3, 4]]",
        "solution": "IA=A.",
    },
    {
        "concept_id": "math.number_theory",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "applied_exercise",
        "prompt": "gcd(24, 18) is?",
        "answer": "6",
        "solution": "Euclid: 24=1*18+6, 18=3*6+0.",
        "numeric": {"got": 6, "expected": 6},
    },
    {
        "concept_id": "math.number_theory",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "prompt": "A student says 15 is prime because it is odd. Correction?",
        "answer": "15=3*5; odd composites exist.",
        "solution": "Primality is about factors, not parity (except 2).",
    },
    {
        "concept_id": "math.statistics",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "prompt": "Data 1, 2, 3, 100. A student reports the mean as a typical value. Why is the median often better here?",
        "answer": "The mean is pulled by 100; the median 2.5 (or 2/3 depending on convention) is robust.",
        "solution": "For even n, median is average of the two central values: (2+3)/2=2.5.",
        "numeric": {"got": 2.5, "expected": 2.5},
    },
    {
        "concept_id": "math.sequences",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "prompt": "An arithmetic sequence 3, 6, 12... a student used a=3, d=3. What is wrong?",
        "answer": "The differences are 3 then 6; it is geometric with ratio 2, not arithmetic.",
        "solution": "Arithmetic needs constant difference.",
    },
    {
        "concept_id": "math.sequences",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "simple_exercise",
        "prompt": "Geometric: first term 3, ratio 2, 4 terms. Sum?",
        "answer": "45",
        "solution": "3(2^4-1)/(2-1)=45.",
        "numeric": {"got": 45, "expected": 45},
    },
    {
        "concept_id": "science.method",
        "domain": "science",
        "education_level": "middle_school",
        "task_type": "debugging_exercise",
        "prompt": "A student 'proves' a fertilizer works by showing treated plants grew. What missing piece is the control?",
        "answer": "Untreated plants grown otherwise the same; growth happens without fertilizer too.",
        "solution": "Compare to control. Anecdote is not a controlled test.",
    },
    {
        "concept_id": "science.method",
        "domain": "science",
        "education_level": "middle_school",
        "task_type": "concept_explanation",
        "prompt": "Why is replication more than repeating a measurement on the same plant five times in one minute?",
        "answer": "Independent replicates capture biological/plot variation, not just instrument jitter.",
        "solution": "Pseudoreplication pretends dependent data are independent.",
    },
    {
        "concept_id": "science.newton",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "prompt": "A 2 kg object with net force 0 is said to 'stop'. What does Newton actually say?",
        "answer": "It keeps constant velocity, which may be zero or nonzero.",
        "solution": "F_net=0 means a=0, not v=0.",
    },
    {
        "concept_id": "science.newton",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "applied_exercise",
        "prompt": "Net force 20 N on 5 kg. Acceleration magnitude?",
        "answer": "4",
        "solution": "a=F/m=4 m/s^2.",
        "numeric": {"got": 4, "expected": 4},
    },
    {
        "concept_id": "science.energy",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "prompt": "A student sets mgh = 1/2 mv^2 and cancels m, then uses g=10, h=5, and reports v=10 forgetting the 2. Compute the actual v from v=sqrt(2gh).",
        "answer": "10",
        "solution": "v=sqrt(2*10*5)=sqrt(100)=10. If they dropped the 2 they would get sqrt(50).",
        "numeric": {"got": 10, "expected": 10},
    },
    {
        "concept_id": "science.energy",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "applied_exercise",
        "prompt": "Work = force times displacement along the force. 8 N through 3 m, parallel. Work in J?",
        "answer": "24",
        "solution": "W=Fd=24 J.",
        "numeric": {"got": 24, "expected": 24},
    },
    {
        "concept_id": "science.circuits",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "prompt": "Two 4 ohm resistors in series are treated as 4 ohm total. Correction and series equivalent?",
        "answer": "Series adds; equivalent is 8 ohm.",
        "solution": "Parallel would be 2 ohm. Series 4+4=8.",
        "numeric": {"got": 8, "expected": 8},
    },
    {
        "concept_id": "science.circuits",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "applied_exercise",
        "prompt": "Power P=IV. 3 A through 6 V. Power in W?",
        "answer": "18",
        "solution": "P=18 W.",
        "numeric": {"got": 18, "expected": 18},
    },
    {
        "concept_id": "science.stoichiometry",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "applied_exercise",
        "prompt": "2H2 + O2 -> 2H2O. How many moles of O2 are needed for 4 mol H2?",
        "answer": "2",
        "solution": "Ratio H2:O2 is 2:1, so 4 mol H2 need 2 mol O2.",
        "numeric": {"got": 2, "expected": 2},
    },
    {
        "concept_id": "science.stoichiometry",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "prompt": "A student conserves mass by counting moles of molecules equal on both sides of 2H2+O2->2H2O (3 vs 2). What should be conserved?",
        "answer": "Atoms of each element, not the count of molecules.",
        "solution": "4 H atoms and 2 O atoms on both sides.",
    },
    {
        "concept_id": "science.waves",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "applied_exercise",
        "prompt": "Period 0.2 s. Frequency in Hz?",
        "answer": "5",
        "solution": "f=1/T=5 Hz.",
        "numeric": {"got": 5, "expected": 5},
    },
    {
        "concept_id": "science.waves",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "prompt": "A student adds two amplitudes 3 and 4 and reports intensity scaled by 7. For coherent in-phase waves, intensity scales with amplitude squared. If amplitude becomes 7, intensity scales by what factor vs amplitude 3?",
        "answer": "49/9",
        "solution": "I ~ A^2 so (7/3)^2=49/9.",
        "numeric": {"got": 5.444444444, "expected": 5.444444444},
    },
    {
        "concept_id": "science.thermo",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "prompt": "Heat and temperature are used interchangeably. Give one sentence distinguishing them, then compute Q=mcΔT for m=2, c=1, ΔT=3 (arbitrary units).",
        "answer": "6",
        "solution": "Temperature is a state; heat is energy transferred. Q=2*1*3=6.",
        "numeric": {"got": 6, "expected": 6},
    },
    {
        "concept_id": "science.optics",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "applied_exercise",
        "prompt": "Thin lens: f=10 cm, object at 20 cm. Image distance v from 1/f=1/v+1/u with u=20. What is v in cm?",
        "answer": "20",
        "solution": "1/10=1/v+1/20 => 1/v=1/20 => v=20.",
        "numeric": {"got": 20, "expected": 20},
    },
    {
        "concept_id": "science.optics",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "prompt": "A student treats a diverging lens like a converging one with positive f in the same sign convention without flipping f. What sign should f have for a diverging lens in the common Cartesian convention used in many intro courses?",
        "answer": "negative",
        "solution": "Diverging lenses have negative focal length in that convention.",
    },
    {
        "concept_id": "science.genetics",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "applied_exercise",
        "prompt": "AaBb x aabb independent assortment. What fraction of offspring are aabb?",
        "answer": "1/4",
        "solution": "Each locus is a testcross 1/2 recessive; 1/2 * 1/2 = 1/4.",
        "numeric": {"got": 0.25, "expected": 0.25},
    },
    {
        "concept_id": "python.comprehensions",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "What list does `[n*n for n in range(4) if n%2==0]` produce?",
        "answer": "[0, 4]",
        "solution": "n=0 and n=2.",
    },
    {
        "concept_id": "python.comprehensions",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "applied_exercise",
        "language": "python",
        "prompt": "Why is a list comprehension a bad place to call a function that writes to disk for each item?",
        "answer": "Comprehensions hide side effects; a for-loop makes the I/O obvious and easier to handle errors.",
        "solution": "Use comprehensions for pure mapping/filtering.",
    },
    {
        "concept_id": "python.decorators",
        "domain": "programming",
        "education_level": "undergraduate",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "Without functools.wraps, what happens to `fn.__name__` after `@decorator`?",
        "answer": "It becomes the wrapper's name, not the original function's.",
        "solution": "wraps copies metadata. Debugging and docs break otherwise.",
    },
    {
        "concept_id": "python.context_managers",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "Does `__exit__` run if the with-block raises? Yes or no.",
        "answer": "yes",
        "solution": "That is why files still close on error.",
    },
    {
        "concept_id": "python.typing",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "At runtime, does `def f(x: int)` reject f('a') by itself in stock CPython?",
        "answer": "no",
        "solution": "Annotations are not checked at runtime unless a library does so.",
    },
    {
        "concept_id": "python.file_io",
        "domain": "programming",
        "education_level": "high_school",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "Why pass encoding='utf-8' to open() on Windows for a UTF-8 file?",
        "answer": "The default encoding is locale-dependent and can mis-decode bytes.",
        "solution": "Be explicit for portable text I/O.",
    },
    {
        "concept_id": "cs.graphs",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "BFS vs DFS for shortest hops on an unweighted graph: which, and why?",
        "answer": "BFS; first time you reach the node is a minimum hop count.",
        "solution": "DFS can find a long path first.",
    },
    {
        "concept_id": "cs.graphs",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "applied_exercise",
        "language": "python",
        "prompt": "Adjacency matrix vs list for a sparse graph with n=10^5, m=10^5: which stores fewer edge slots, roughly?",
        "answer": "Adjacency lists; matrix is Theta(n^2) entries.",
        "solution": "Lists are Theta(n+m).",
    },
    {
        "concept_id": "cs.sorting",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "applied_exercise",
        "language": "python",
        "prompt": "When do you need a stable sort for a two-key sort (sort by last name, then keep first-name order)?",
        "answer": "Sort by the secondary key first, then stable-sort by the primary key.",
        "solution": "Unstable primary sort can scramble equal last names.",
    },
    {
        "concept_id": "cs.dynamic_programming",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "What two properties make a problem a DP candidate?",
        "answer": "Optimal substructure and overlapping subproblems.",
        "solution": "Without overlap, divide-and-conquer suffices. Without optimal substructure, greed/DP recurrences fail.",
    },
    {
        "concept_id": "cs.concurrency",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "Name the bug when two threads do `x = x + 1` on a shared int without a lock.",
        "answer": "lost update / race",
        "solution": "Read-modify-write is not atomic. Use a lock or an atomic counter.",
    },
    {
        "concept_id": "cs.os",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "User code calls read(). Who switches to kernel mode, the compiler or the syscall?",
        "answer": "the syscall / trap into the kernel",
        "solution": "The compiler emits a syscall; the processor exception/syscall instruction enters the kernel.",
    },
    {
        "concept_id": "sql.indexes",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "simple_exercise",
        "language": "sql",
        "prompt": "A unique index on email: can two rows have NULL email in SQL systems that treat NULL as distinct in unique indexes? Answer: it depends / yes-in-some / never. Pick 'it depends'.",
        "answer": "it depends",
        "solution": "SQL unique constraints historically allow multiple NULLs; engines differ. Do not assume.",
    },
    {
        "concept_id": "sql.indexes",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "applied_exercise",
        "language": "sql",
        "prompt": "Why can an index on (last, first) serve `WHERE last=?` but not `WHERE first=?` well?",
        "answer": "A composite B-tree is ordered by the leftmost prefix first.",
        "solution": "Leading-column predicates can range-scan. Isolated right columns cannot.",
    },
]
