"""Additional original coverage tasks so concepts are not one-type thin.

Each prompt is a distinct problem, not a paraphrase of another bank item.
"""

from __future__ import annotations

COVERAGE_SPECS_V1: list[dict] = [
    {
        "concept_id": "python.modules",
        "domain": "programming",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "language": "python",
        "prompt": "A package directory has foo.py but no __init__.py on Python 3.3+. Why can `import pack.foo` still work, and when would it fail?",
        "answer": "Namespace packages allow import without __init__.py. It fails if another pack on sys.path is a regular package that hides the namespace, or if the directory is not on sys.path.",
        "solution": "PEP 420 namespace packages. Explicit __init__.py still makes a regular package. Path order decides which pack wins.",
    },
    {
        "concept_id": "python.iterators",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "debugging_exercise",
        "language": "python",
        "prompt": "Code does `it = iter(xs); list(it); list(it)` and the second list is empty. Is that a bug in list()?",
        "answer": "No. The iterator was exhausted by the first list() call. A second pass needs a new iterator.",
        "solution": "list(it) consumes it. Call iter(xs) again, or keep the original sequence.",
    },
    {
        "concept_id": "cs.algorithms",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "applied_exercise",
        "language": "python",
        "prompt": "You need the k smallest elements of n numbers, k much smaller than n. Why is a size-k heap often better than fully sorting?",
        "answer": "Full sort is Theta(n log n). A bounded heap is O(n log k), which is smaller when k << n.",
        "solution": "Each of n insertions/evictions costs O(log k) on a heap of size k. Sorting pays for order you will discard.",
    },
    {
        "concept_id": "cs.http",
        "domain": "computer_science",
        "education_level": "introductory_college",
        "task_type": "applied_exercise",
        "language": "python",
        "prompt": "A client retries a POST that created a resource after a timeout with no response. What can go wrong, and what property would make the retry safe?",
        "answer": "The first POST may have succeeded, so a retry can create a duplicate. Idempotent methods or client-generated idempotency keys make retries safe.",
        "solution": "Timeouts are not failures. POST is not idempotent by default. PUT to a known URL or an Idempotency-Key header addresses duplicate creates.",
    },
    {
        "concept_id": "cs.git",
        "domain": "computer_science",
        "education_level": "introductory_college",
        "task_type": "debugging_exercise",
        "language": "python",
        "prompt": "Two people edited the same function on different branches. A merge stops with conflict markers. What does Git not know, and what must a human decide?",
        "answer": "Git only sees overlapping text hunks. It cannot tell which behaviour is intended. A human must combine or choose the correct function body and test it.",
        "solution": "Conflict markers are not a compiler. Resolve, remove markers, and run tests before committing the merge.",
    },
    {
        "concept_id": "rust.ownership",
        "domain": "programming",
        "education_level": "undergraduate",
        "task_type": "debugging_exercise",
        "language": "rust",
        "prompt": "This snippet fails to compile: `let s = String::from(\"hi\"); let t = s; println!(\"{}\", s);`. What is the error class, and how do you print both?",
        "answer": "Use-after-move. Clone if you need two owned Strings, or print before moving, or borrow with &s.",
        "solution": "s was moved into t. Clone costs an allocation. Borrowing lets both names observe the same value without a second owner.",
    },
    {
        "concept_id": "go.concurrency",
        "domain": "programming",
        "education_level": "undergraduate",
        "task_type": "debugging_exercise",
        "language": "go",
        "prompt": "A goroutine sends on an unbuffered channel and the main function returns without receiving. What happens to that send, and how do you wait correctly?",
        "answer": "The send blocks forever if nobody receives; when main returns the process exits and the work is lost. Wait with a receive, WaitGroup, or a done channel.",
        "solution": "Unbuffered send synchronizes with a receive. Exiting main does not drain other goroutines.",
    },
    {
        "concept_id": "math.functions",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "simple_exercise",
        "prompt": "f(x)=2x+1 and g(x)=x^2. What is (f ∘ g)(3)?",
        "answer": "19",
        "solution": "g(3)=9, then f(9)=19.",
        "numeric": {"got": 19, "expected": 19},
    },
    {
        "concept_id": "math.trigonometry",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "concept_explanation",
        "prompt": "Why must sine of an angle in a right triangle be at most 1?",
        "answer": "Opposite is a side of the triangle, so it cannot exceed the hypotenuse. Their ratio is at most 1.",
        "solution": "sin = opposite/hypotenuse. Sides are positive and opposite ≤ hypotenuse.",
    },
    {
        "concept_id": "math.discrete",
        "domain": "mathematics",
        "education_level": "undergraduate",
        "task_type": "concept_explanation",
        "prompt": "Why is the number of subsets of an n-element set 2^n, including the empty set?",
        "answer": "Each element is independently in or out, giving 2 choices per element, so 2^n subsets.",
        "solution": "The empty set is the all-out choice. The full set is the all-in choice.",
    },
    {
        "concept_id": "math.probability",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "concept_explanation",
        "prompt": "Why can you not add P(A) and P(B) to get P(A or B) when A and B can both happen?",
        "answer": "The intersection would be counted twice. Use P(A)+P(B)-P(A and B).",
        "solution": "Inclusion-exclusion. Independent events still have a nonempty intersection in general.",
    },
    {
        "concept_id": "math.linear_algebra",
        "domain": "mathematics",
        "education_level": "undergraduate",
        "task_type": "concept_explanation",
        "prompt": "Why does a 2x2 matrix with determinant 0 fail to have an inverse?",
        "answer": "Determinant 0 means the columns are linearly dependent, so the map collapses a line to a point and is not injective.",
        "solution": "Invertible linear maps are bijective. A collapsed direction cannot be undone.",
    },
    {
        "concept_id": "math.number_theory",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "concept_explanation",
        "prompt": "Why does Euclid's algorithm terminate when computing gcd(a,b) for positive integers?",
        "answer": "Each remainder is a strictly smaller nonnegative integer, so the sequence of remainders cannot descend forever.",
        "solution": "Well-ordering of nonnegative integers. gcd(a,b)=gcd(b, a mod b) preserves the gcd.",
    },
    {
        "concept_id": "science.energy",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "concept_explanation",
        "prompt": "Why can kinetic energy never be negative in classical mechanics while gravitational potential can be set negative?",
        "answer": "KE is (1/2)mv^2, a square. Potential energy is defined up to an additive constant, so the zero point is a convention.",
        "solution": "Speed squared is nonnegative. You may choose PE=0 at infinity, making bound orbits negative.",
    },
    {
        "concept_id": "science.circuits",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "concept_explanation",
        "prompt": "Why do two equal resistors in parallel draw more current from a fixed voltage than one of them alone?",
        "answer": "Parallel equivalent resistance is half of one resistor, so I=V/R_eq is larger.",
        "solution": "Each branch carries V/R. Two branches carry 2V/R. Equivalent is R/2.",
    },
    {
        "concept_id": "science.stoichiometry",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "concept_explanation",
        "prompt": "Why can a limiting reactant stop a reaction even if the other reactant is still present?",
        "answer": "The balanced equation requires a fixed mole ratio. When one reactant is used up, leftover excess cannot form more product.",
        "solution": "Stoichiometry is a ratio, not 'mix until gone'. Compute moles and compare to coefficients.",
    },
    {
        "concept_id": "science.waves",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "concept_explanation",
        "prompt": "If you double frequency while holding wave speed fixed, what happens to wavelength, and why?",
        "answer": "Wavelength halves because v=fλ with v constant.",
        "solution": "λ=v/f. Doubling f halves λ.",
    },
    {
        "concept_id": "python.collections",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "debugging_exercise",
        "language": "python",
        "prompt": "Code does `seen = [];` then `if x not in seen: seen.append(x)` inside a hot loop of 10^6 items. What is the complexity problem, and what structure fixes membership?",
        "answer": "Membership in a list is linear, so the loop can be quadratic. A set gives average-case O(1) membership.",
        "solution": "Use a set for 'have I seen this hashable x'. Lists preserve order if you also need insertion order; dict/set already do in modern CPython.",
    },
    {
        "concept_id": "python.loops",
        "domain": "programming",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "language": "python",
        "prompt": "A while loop increments i only inside an `if` that sometimes fails, and i starts at 0. What class of bug is this, and what is the usual repair?",
        "answer": "A possible infinite loop: i may never change. Increment in a path that always runs, or add a termination condition that does not depend on the skipped branch.",
        "solution": "Loop variables must progress. Put i += 1 outside the failing if, or restructure.",
    },
    {
        "concept_id": "python.variables",
        "domain": "programming",
        "education_level": "high_school",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "After `x = 4; y = x; x = 5`, what is y, and did y change because x changed?",
        "answer": "y is 4. Integers are immutable; x was rebound, y was not.",
        "solution": "Rebinding x does not follow other names. y still refers to 4.",
        "numeric": {"got": 4, "expected": 4},
    },
    {
        "concept_id": "math.arithmetic",
        "domain": "mathematics",
        "education_level": "k5",
        "task_type": "concept_explanation",
        "prompt": "Why is 1/2 + 1/3 not 2/5?",
        "answer": "You cannot add numerators and denominators separately. Common denominator 6 gives 3/6+2/6=5/6.",
        "solution": "Fractions are ratios. 2/5 would be a different ratio, not the sum of halves and thirds.",
    },
    {
        "concept_id": "math.calculus",
        "domain": "mathematics",
        "education_level": "introductory_college",
        "task_type": "simple_exercise",
        "prompt": "What is the derivative of x^3 with respect to x?",
        "answer": "3*x**2",
        "solution": "Power rule: n x^{n-1}. Here n=3.",
        "sympy": {"got": "3*x**2", "expected": "3*x**2"},
    },
    {
        "concept_id": "science.newton",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "concept_explanation",
        "prompt": "If net force is zero, why can an object still be moving?",
        "answer": "Newton's first law: zero net force means constant velocity, which may be nonzero.",
        "solution": "Force changes velocity. Zero net force means no acceleration, not necessarily rest.",
    },
    {
        "concept_id": "python.comprehensions",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "concept_explanation",
        "language": "python",
        "prompt": "What is the difference between `[x*x for x in xs if x>0]` and a generator expression `(x*x for x in xs if x>0)`?",
        "answer": "The list comprehension materializes every result immediately. The generator yields values lazily and can be iterated only once.",
        "solution": "Use the list when you need len, reuse, or random access. Use the generator for streaming large sequences.",
    },
    {
        "concept_id": "python.comprehensions",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "What list does `[n for n in range(6) if n % 2 == 0]` produce?",
        "answer": "[0, 2, 4]",
        "solution": "range(6) is 0..5. The filter keeps evens.",
    },
    {
        "concept_id": "python.decorators",
        "domain": "programming",
        "education_level": "undergraduate",
        "task_type": "concept_explanation",
        "language": "python",
        "prompt": "What does `@f` above `def g():` actually do at definition time?",
        "answer": "It replaces g with the result of f(g). f must return a callable (usually a wrapper).",
        "solution": "`def g` binds the original function, then `g = f(g)` runs. That is why argumentless decorators are callables that take a function.",
    },
    {
        "concept_id": "python.decorators",
        "domain": "programming",
        "education_level": "undergraduate",
        "task_type": "debugging_exercise",
        "language": "python",
        "prompt": "A timing decorator's wrapper is named `inner` and tests assert `fn.__name__ == 'compute'`. Why do they fail, and what one-line fix is conventional?",
        "answer": "The wrapper overwrote __name__. Apply @functools.wraps(func) on the inner function.",
        "solution": "wraps copies __name__, __doc__, and __module__ from the wrapped function.",
    },
    {
        "concept_id": "python.context_managers",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "concept_explanation",
        "language": "python",
        "prompt": "Why does `with open(path) as f:` close the file even if the body raises?",
        "answer": "__exit__ runs during stack unwind, so close happens on both success and exception paths.",
        "solution": "The with-statement is try/finally around __enter__/__exit__. You still see the exception unless __exit__ swallows it.",
    },
    {
        "concept_id": "python.context_managers",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "applied_exercise",
        "language": "python",
        "prompt": "When should you write a context manager for a lock versus calling acquire/release by hand?",
        "answer": "Use with lock: so release runs if the critical section raises. Hand-paired acquire/release is easy to skip on error paths.",
        "solution": "Locks, files, and sessions are the usual with-targets because cleanup must be reliable.",
    },
    {
        "concept_id": "python.typing",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "concept_explanation",
        "language": "python",
        "prompt": "Does `x: list[int] = []` prevent appending a string at runtime in CPython?",
        "answer": "No. The annotation is not enforced at runtime. A type checker can still flag append('a').",
        "solution": "Hints document intent. Runtime checks need isinstance or a validator.",
    },
    {
        "concept_id": "python.typing",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "applied_exercise",
        "language": "python",
        "prompt": "Why is `Optional[str]` written as `str | None` in modern Python, and what does it allow that `str` does not?",
        "answer": "It documents that None is a legal value. A plain str hint tells checkers that None is a mistake.",
        "solution": "Callers must handle None. The union is the type, not a runtime conversion.",
    },
    {
        "concept_id": "python.file_io",
        "domain": "programming",
        "education_level": "high_school",
        "task_type": "concept_explanation",
        "language": "python",
        "prompt": "Why should you pass encoding='utf-8' when opening text files rather than relying on the default?",
        "answer": "The default encoding is locale-dependent, so the same bytes can decode differently on another machine.",
        "solution": "Pin UTF-8 for portable text. Binary mode is for bytes that are not text.",
    },
    {
        "concept_id": "python.file_io",
        "domain": "programming",
        "education_level": "high_school",
        "task_type": "debugging_exercise",
        "language": "python",
        "prompt": "A script writes JSON with `open(path,'w')` on Windows and a later reader on Linux sees garbage around non-ASCII. What went wrong?",
        "answer": "Text mode used a locale encoding on write. Readers assuming UTF-8 mis-decode. Write with encoding='utf-8'.",
        "solution": "JSON should be UTF-8. Never depend on the ANSI code page for interchange.",
    },
    {
        "concept_id": "cs.graphs",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "concept_explanation",
        "language": "python",
        "prompt": "Why does BFS find a shortest path in an unweighted graph while DFS generally does not?",
        "answer": "BFS expands by hop count, so the first time you reach a node is via a minimum number of edges. DFS can dive down a long path first.",
        "solution": "Unweighted shortest path = fewest edges. Weights need Dijkstra or Bellman-Ford instead.",
    },
    {
        "concept_id": "cs.graphs",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "An undirected graph has 4 vertices and is a square (cycle of 4). How many edges does it have?",
        "answer": "4",
        "solution": "A C4 has four vertices and four edges.",
        "numeric": {"got": 4, "expected": 4},
    },
    {
        "concept_id": "cs.sorting",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "concept_explanation",
        "language": "python",
        "prompt": "What does it mean for a sort to be stable, and name one algorithm that is typically stable?",
        "answer": "Equal keys keep their original relative order. Mergesort is typically stable; heapsort is not.",
        "solution": "Stability matters when you sort by one key and then another. Unstable sorts can scramble the first key's order.",
    },
    {
        "concept_id": "cs.sorting",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "applied_exercise",
        "language": "python",
        "prompt": "Why is comparison sorting Omega(n log n) in the worst case in the comparison model?",
        "answer": "There are n! possible orders. Each comparison has two outcomes, so you need log2(n!) comparisons, which is Theta(n log n) by Stirling.",
        "solution": "Decision trees of height h distinguish at most 2^h leaves. n! > 2^{o(n log n)}.",
    },
    {
        "concept_id": "cs.dynamic_programming",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "concept_explanation",
        "language": "python",
        "prompt": "What two properties make a problem a candidate for dynamic programming?",
        "answer": "Optimal substructure and overlapping subproblems. You store answers to repeated subproblems instead of recomputing them.",
        "solution": "If subproblems do not overlap, divide-and-conquer without a table is enough. If they do, memoization or a bottom-up table pays off.",
    },
    {
        "concept_id": "cs.dynamic_programming",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "Naive recursive Fibonacci without memoization computes F(5). How many times is F(3) evaluated in the standard tree F(n)=F(n-1)+F(n-2) with F(0),F(1) bases?",
        "answer": "2",
        "solution": "F(5) calls F(4) and F(3). F(4) calls F(3) and F(2). F(3) appears twice.",
        "numeric": {"got": 2, "expected": 2},
    },
    {
        "concept_id": "cs.concurrency",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "concept_explanation",
        "language": "python",
        "prompt": "What is a race condition, in one operational sentence?",
        "answer": "The outcome depends on unsynchronized interleaving of accesses to shared state, so two runs with the same inputs can disagree.",
        "solution": "Fix by keeping data thread-confined, using locks/atomics, or avoiding shared mutation.",
    },
    {
        "concept_id": "cs.concurrency",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "debugging_exercise",
        "language": "python",
        "prompt": "Two threads do `x = x + 1` on a shared integer without a lock. Why can the final x be 1 after both have 'incremented' once from 0?",
        "answer": "Both read 0, both write 1. The increments are not atomic.",
        "solution": "Read-modify-write is three steps. A lock, or an atomic add, makes the pair one critical section.",
    },
    {
        "concept_id": "cs.os",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "concept_explanation",
        "language": "python",
        "prompt": "Why can two processes not see each other's local variables even though they run on the same CPU?",
        "answer": "Each process has its own virtual address space. The OS maps those addresses to physical memory separately.",
        "solution": "Isolation is a memory-management invariant. Shared memory exists only if explicitly requested.",
    },
    {
        "concept_id": "cs.os",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "applied_exercise",
        "language": "python",
        "prompt": "A user program calls read() and the kernel copies bytes into the process buffer. Why must that copy (or an equivalent mapping) be mediated by the kernel?",
        "answer": "User code is not allowed to access device memory or other processes' pages directly. The syscall is the controlled crossing.",
        "solution": "Protection rings / user vs supervisor mode. Drivers and page tables live on the kernel side.",
    },
    {
        "concept_id": "javascript.promises",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "concept_explanation",
        "language": "javascript",
        "prompt": "What is the difference between `fn().then(handler)` and `await fn()` inside an async function?",
        "answer": "Both wait for the Promise. await pauses the async function and resumes with the fulfilled value or throws on rejection. then registers a callback without using throw.",
        "solution": "await is syntax over Promises. Unhandled rejection vs try/catch is the practical difference.",
    },
    {
        "concept_id": "javascript.promises",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "debugging_exercise",
        "language": "javascript",
        "prompt": "Code does `promise.then(ok); promise.then(alsoOk)` expecting the executor to run twice. Why does the network request still happen once?",
        "answer": "The Promise caches one settlement. Additional then-handlers observe it; they do not restart the executor.",
        "solution": "To start work twice, call the factory twice. Sharing one Promise is how you join waiters.",
    },
    {
        "concept_id": "math.statistics",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "simple_exercise",
        "prompt": "What is the mean of 2, 4, 6, 8?",
        "answer": "5",
        "solution": "(2+4+6+8)/4 = 20/4 = 5.",
        "numeric": {"got": 5, "expected": 5},
    },
    {
        "concept_id": "math.statistics",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "applied_exercise",
        "prompt": "A class scored 70, 72, 74, 99. Why is the median a better 'typical score' headline than the mean?",
        "answer": "The 99 pulls the mean up. The median 73 sits with the cluster of typical scores.",
        "solution": "Mean=(70+72+74+99)/4=78.75. Sorted median is average of 72 and 74 = 73.",
    },
    {
        "concept_id": "math.sequences",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "simple_exercise",
        "prompt": "An arithmetic sequence has first term 3 and common difference 5. What is the 4th term?",
        "answer": "18",
        "solution": "a_n = a_1 + (n-1)d = 3 + 3*5 = 18.",
        "numeric": {"got": 18, "expected": 18},
    },
    {
        "concept_id": "math.sequences",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "applied_exercise",
        "prompt": "A geometric series has first term 2 and ratio 1/2. What is the infinite sum, if it exists?",
        "answer": "4",
        "solution": "For |r|<1, S=a/(1-r)=2/(1-1/2)=4.",
        "numeric": {"got": 4, "expected": 4},
    },
    {
        "concept_id": "science.thermo",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "simple_exercise",
        "prompt": "How much heat in joules raises 2 kg of water by 3 K if c=4184 J/(kg·K)?",
        "answer": "25104",
        "solution": "Q=mcΔT=2*4184*3=25104 J.",
        "numeric": {"got": 25104, "expected": 25104},
    },
    {
        "concept_id": "science.thermo",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "concept_explanation",
        "prompt": "Why does a metal spoon in hot tea feel hotter than a wooden one at the same temperature after a minute?",
        "answer": "Metal conducts heat to your hand faster. Temperature can match; heat flow (conductivity) differs.",
        "solution": "Thermal conductivity, not a different thermometer reading of the bulk tea, explains the sensation.",
    },
    {
        "concept_id": "science.optics",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "simple_exercise",
        "prompt": "A converging lens has focal length 10 cm. A real object is 20 cm from the lens. Using 1/f = 1/v + 1/u with positive object and image distances, what is the image distance v in cm?",
        "answer": "20",
        "solution": "1/10 = 1/v + 1/20, so 1/v = 1/10 - 1/20 = 1/20, hence v = 20.",
        "numeric": {"got": 20, "expected": 20},
    },
    {
        "concept_id": "science.optics",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "concept_explanation",
        "prompt": "Why does a magnifying glass form a real inverted image of a distant window on a card, but a virtual upright image of nearby text for your eye?",
        "answer": "Distant objects sit beyond 2f, producing a real inverted image. Nearby text inside f produces a virtual upright image that the eye can focus.",
        "solution": "Object distance relative to focal length switches the image type. Same lens, different u.",
    },
    {
        "concept_id": "science.genetics",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "simple_exercise",
        "prompt": "Both parents are heterozygous Aa for a dominant trait. What fraction of offspring are expected aa?",
        "answer": "1/4",
        "solution": "Punnett: AA, Aa, Aa, aa. One of four is aa.",
        "numeric": {"got": 0.25, "expected": 0.25},
    },
    {
        "concept_id": "science.genetics",
        "domain": "science",
        "education_level": "high_school",
        "task_type": "concept_explanation",
        "prompt": "Why does a recessive disease skip generations in a pedigree more often than a dominant one?",
        "answer": "Carriers (heterozygotes) do not show the recessive trait, so affected children can be born to unaffected parents.",
        "solution": "Dominant traits appear whenever one copy is present, so they show in every generation they are transmitted (with complete penetrance).",
    },
    {
        "concept_id": "sql.indexes",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "concept_explanation",
        "language": "sql",
        "prompt": "Why can an index make writes slower even when it makes some reads faster?",
        "answer": "Each insert/update/delete must maintain the index structure in addition to the heap/table row.",
        "solution": "Indexes are extra data. Point lookups win; bulk loads and high-churn tables pay the maintenance.",
    },
    {
        "concept_id": "sql.indexes",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "applied_exercise",
        "language": "sql",
        "prompt": "A query is `WHERE lower(email) = 'a@b.com'` and the index is on email. Why might the planner still scan?",
        "answer": "Applying a function to the column prevents a simple B-tree lookup on email. Index the expression or store a canonical form.",
        "solution": "Predicate and index keys must match. lower(email) is not email.",
    },
    {
        "concept_id": "python.classes",
        "domain": "programming",
        "education_level": "introductory_college",
        "task_type": "debugging_exercise",
        "language": "python",
        "prompt": "A subclass forgets to call super().__init__ and then uses self.x set only in the parent __init__. What happens on the first use of self.x?",
        "answer": "AttributeError: the instance never received x. Parent initialization did not run.",
        "solution": "Call super().__init__ (or duplicate the required setup) before using inherited attributes.",
    },
    {
        "concept_id": "math.algebra",
        "domain": "mathematics",
        "education_level": "high_school",
        "task_type": "applied_exercise",
        "prompt": "A rectangle's length is 3 more than its width. Perimeter is 26. What is the width?",
        "answer": "5",
        "solution": "2(w+3)+2w=26 => 4w+6=26 => 4w=20 => w=5.",
        "numeric": {"got": 5, "expected": 5},
    },
    {
        "concept_id": "python.functions",
        "domain": "programming",
        "education_level": "high_school",
        "task_type": "concept_explanation",
        "language": "python",
        "prompt": "Why does returning a list from a function not copy it unless you copy explicitly?",
        "answer": "Return passes the object reference. Caller and callee can share the same mutable list.",
        "solution": "If isolation is required, return list(xs) or xs.copy(). Immutables cannot be mutated in place.",
    },
    {
        "concept_id": "cs.data_structures",
        "domain": "computer_science",
        "education_level": "undergraduate",
        "task_type": "simple_exercise",
        "language": "python",
        "prompt": "A singly linked list has 4 nodes. How many next-pointer follows, starting at the head, reach the last node?",
        "answer": "3",
        "solution": "From the first node you take 3 hops to the fourth.",
        "numeric": {"got": 3, "expected": 3},
    },
]
