"""v1.0.1 extra original curriculum tasks (inspired_by, not scraped copies)."""

from __future__ import annotations

EXTRA_TASKS_V101: dict[str, list[dict]] = {
    "khan_academy_computing": [
        {
            "task_type": "simple_exercise",
            "concept_id": "python.loops",
            "language": "python",
            "prompt": "How many numbers does `list(range(1, 8, 2))` contain?",
            "answer": "4",
            "solution": "1,3,5,7.",
            "numeric": {"got": 4, "expected": 4},
        },
        {
            "task_type": "applied_exercise",
            "concept_id": "python.functions",
            "language": "python",
            "prompt": "A tracing exercise: def add(a,b): return a+b. What is add(add(1,2), 3)?",
            "answer": "6",
            "solution": "Inner add is 3, then 3+3=6.",
            "numeric": {"got": 6, "expected": 6},
        },
    ],
    "mit_opencourseware": [
        {
            "task_type": "simple_exercise",
            "concept_id": "cs.sorting",
            "language": "python",
            "prompt": "Mergesort split of n=8: how many elements in each half after one even split?",
            "answer": "4",
            "solution": "Even n splits into n/2 and n/2.",
            "numeric": {"got": 4, "expected": 4},
        },
        {
            "task_type": "debugging_exercise",
            "concept_id": "cs.dynamic_programming",
            "language": "python",
            "prompt": "A DP table for shortest paths is filled in random node order on a DAG. What can go wrong?",
            "answer": "A node may be processed before its predecessors, so subproblems are incomplete.",
            "solution": "Process in topological order (or relax like Bellman-Ford).",
        },
    ],
    "harvard_cs50": [
        {
            "task_type": "applied_exercise",
            "concept_id": "cs.os",
            "language": "c",
            "prompt": "Why is forgetting to free a heap buffer in a long-running C server a problem even if the OS will reclaim memory at exit?",
            "answer": "The process may never exit; the leak grows with requests.",
            "solution": "Match malloc/free on the request path. Exit reclamation does not help a daemon.",
        },
        {
            "task_type": "debugging_exercise",
            "concept_id": "python.file_io",
            "language": "c",
            "prompt": "A C program reads a file with `while(fgets)` and treats a missing newline on the last line as a bug. Is it?",
            "answer": "No; POSIX text files may omit the final newline. Handle both.",
            "solution": "Do not require a newline to accept the last record.",
        },
    ],
    "openstax": [
        {
            "task_type": "simple_exercise",
            "concept_id": "math.algebra",
            "prompt": "Solve 5x = 20. x=?",
            "answer": "4",
            "solution": "Divide both sides by 5.",
            "numeric": {"got": 4, "expected": 4},
        },
        {
            "task_type": "applied_exercise",
            "concept_id": "math.geometry",
            "prompt": "A square has perimeter 36. What is the area?",
            "answer": "81",
            "solution": "Side 9, area 81.",
            "numeric": {"got": 81, "expected": 81},
        },
    ],
    "mdn": [
        {
            "task_type": "debugging_exercise",
            "concept_id": "javascript.promises",
            "language": "javascript",
            "prompt": "fetch().then(r => r.json()).then(use) with no catch: a 404 still hits use() with a body. Why?",
            "answer": "fetch only rejects on network failure; HTTP 404 is still a resolved Response.",
            "solution": "Check r.ok before json().",
        },
        {
            "task_type": "simple_exercise",
            "concept_id": "cs.http",
            "language": "javascript",
            "prompt": "Which method is defined as safe: GET or POST?",
            "answer": "GET",
            "solution": "GET should not have side effects. POST is for non-idempotent writes.",
        },
    ],
    "the_odin_project": [
        {
            "task_type": "applied_exercise",
            "concept_id": "javascript.closures",
            "language": "javascript",
            "prompt": "A module pattern returns {inc} that closes over count. Why can callers not assign count directly?",
            "answer": "count is in the lexical environment, not a property of the returned object.",
            "solution": "Only the exported functions see count. That is encapsulation via closure.",
        },
        {
            "task_type": "debugging_exercise",
            "concept_id": "cs.http",
            "language": "javascript",
            "prompt": "A form uses GET and puts a password in the query string. Name one reason POST to HTTPS is preferred.",
            "answer": "Query strings land in logs, history, and Referer; POST body is not in the URL.",
            "solution": "Still use TLS. GET is also cached and bookmarked.",
        },
    ],
    "python_docs": [
        {
            "task_type": "simple_exercise",
            "concept_id": "python.collections",
            "language": "python",
            "prompt": "dict.fromkeys(['a','b'], 0) maps both keys to what value?",
            "answer": "0",
            "solution": "fromkeys uses a shared default value.",
            "numeric": {"got": 0, "expected": 0},
        },
        {
            "task_type": "debugging_exercise",
            "concept_id": "python.iterators",
            "language": "python",
            "prompt": "`list(zip(*[]))` — what happens, and why is unzipping an empty list a corner case?",
            "answer": "It returns [] because there are no rows to zip; *[] is no arguments to zip.",
            "solution": "zip() with no iterables yields empty. Guard empty matrices before unzip.",
        },
    ],
    "rust_docs": [
        {
            "task_type": "simple_exercise",
            "concept_id": "rust.ownership",
            "language": "rust",
            "prompt": "Is i32 Copy? Yes or no.",
            "answer": "yes",
            "solution": "Integer types implement Copy, so assignment does not move them.",
        },
        {
            "task_type": "applied_exercise",
            "concept_id": "rust.ownership",
            "language": "rust",
            "prompt": "Why does Vec<String> move on assignment while Vec<i32> copies the vector header but still moves heap buffers... actually Vec is not Copy. Correct the misconception: does assigning a Vec clone the elements?",
            "answer": "No; Vec assignment moves. Clone is explicit.",
            "solution": "Neither Vec<T> is Copy. Move transfers the pointer. clone() deep-copies.",
        },
    ],
    "go_docs": [
        {
            "task_type": "simple_exercise",
            "concept_id": "go.concurrency",
            "language": "go",
            "prompt": "Does `go f()` wait for f to finish before the next statement? Yes or no.",
            "answer": "no",
            "solution": "It starts a goroutine. Wait with channels or WaitGroup.",
        },
        {
            "task_type": "debugging_exercise",
            "concept_id": "go.concurrency",
            "language": "go",
            "prompt": "A map is written from two goroutines without sync. What is the specified risk?",
            "answer": "Concurrent map writes are undefined / can panic.",
            "solution": "Use a mutex or sync.Map as documented. Do not race on maps.",
        },
    ],
    "w3c_whatwg": [
        {
            "task_type": "simple_exercise",
            "concept_id": "cs.http",
            "language": "html",
            "prompt": "In HTML, is `<img>` a void element that must not have a closing tag in HTML syntax? Yes or no.",
            "answer": "yes",
            "solution": "Void elements have no content. XML/XHTML differs; this item is HTML.",
        },
        {
            "task_type": "applied_exercise",
            "concept_id": "cs.http",
            "language": "html",
            "prompt": "Why is putting a secret in a data-* attribute on a public page still a leak?",
            "answer": "The HTML is delivered to the client; anyone can read the source.",
            "solution": "Secrets belong on the server, not in markup.",
        },
    ],
    "sqlite_docs": [
        {
            "task_type": "simple_exercise",
            "concept_id": "cs.sql",
            "language": "sql",
            "prompt": "SQLite: SELECT typeof(1.5); what type name?",
            "answer": "real",
            "solution": "Floating values are REAL affinity/storage.",
        },
        {
            "task_type": "applied_exercise",
            "concept_id": "sql.indexes",
            "language": "sql",
            "prompt": "Why might `WHERE name LIKE '%son'` not use a normal B-tree index on name?",
            "answer": "A leading wildcard prevents a left-to-right index prefix match.",
            "solution": "LIKE 'son%' can use the index; '%son' generally cannot.",
        },
    ],
    "postgresql_docs": [
        {
            "task_type": "simple_exercise",
            "concept_id": "cs.sql",
            "language": "sql",
            "prompt": "NULL AND TRUE in SQL three-valued logic is what: true, false, or unknown?",
            "answer": "unknown",
            "solution": "AND with unknown and true is unknown.",
        },
        {
            "task_type": "debugging_exercise",
            "concept_id": "cs.sql",
            "language": "sql",
            "prompt": "A unique constraint allows two NULLs in some SQL systems. Why is `WHERE email = NULL` still wrong to find them?",
            "answer": "NULL = NULL is unknown, not true. Use IS NULL.",
            "solution": "Three-valued logic. Equality is not a null test.",
        },
    ],
    "linux_man_pages": [
        {
            "task_type": "simple_exercise",
            "concept_id": "cs.os",
            "language": "c",
            "prompt": "Does a successful write() guarantee the data is on durable storage? Yes or no.",
            "answer": "no",
            "solution": "It may sit in page cache until fsync/fdatasync or equivalent.",
        },
        {
            "task_type": "applied_exercise",
            "concept_id": "cs.os",
            "language": "c",
            "prompt": "Why can `errno` after a failed libc call be overwritten if you printf before checking it?",
            "answer": "printf may itself fail or succeed and change errno.",
            "solution": "Save errno immediately, then log.",
        },
    ],
    "nasa_education": [
        {
            "task_type": "simple_exercise",
            "concept_id": "science.newton",
            "prompt": "Using v=sqrt(2gR) with g=10 m/s² and R=6.4e6 m, what is v rounded to the nearest integer m/s?",
            "answer": "11314",
            "solution": "2gR=1.28e8; sqrt(1.28e8)≈11313.71, which rounds to 11314.",
            "numeric": {"got": 11314, "expected": 11314},
        },
    ],
    "noaa_education": [
        {
            "task_type": "simple_exercise",
            "concept_id": "science.method",
            "prompt": "A tide gauge reads 1.2 m, then 1.5 m. What is the delta in metres?",
            "answer": "0.3",
            "solution": "1.5-1.2=0.3.",
            "numeric": {"got": 0.3, "expected": 0.3},
        },
    ],
    "usgs_education": [
        {
            "task_type": "simple_exercise",
            "concept_id": "science.method",
            "prompt": "A map scale is 1:24000. 2 inches on the map is how many inches on the ground?",
            "answer": "48000",
            "solution": "2*24000=48000 inches.",
            "numeric": {"got": 48000, "expected": 48000},
        },
    ],
    "oer_commons": [
        {
            "task_type": "applied_exercise",
            "concept_id": "science.method",
            "prompt": "Why is 'inspired by a public syllabus' not a license to copy homework text?",
            "answer": "Copyright still covers the wording; inspiration is original tasks with attribution of influence, not quotation.",
            "solution": "Open Reason writes original prompts and sets verbatim false.",
        },
    ],
    "wikibooks": [
        {
            "task_type": "applied_exercise",
            "prompt": "If you paraphrase a CC BY-SA chapter into a dataset row, why might share-alike still attach?",
            "answer": "A close paraphrase can still be a derivative work under SA terms.",
            "solution": "Write original problems. Do not relicense SA text as CC BY 4.0.",
        },
    ],
}
